### ISSUE TITLE
Question: `async_tungstenite` vs `tokio_tungstenite`

### ISSUE THREAD

**Issue by 0xJepsen** [najamelan/ws_stream_tungstenite#17]
to my know the features that `async_tungstenite` was made to support are not supported in `tokio_tungstenite`. It would then make sense to me to switch to `tokio_tungstenite` as it seems like the canonical lib. Am I missing something?

**Comment by najamelan** [comment]
Hi, sorry for the delay. We use `async_tungstenite` because it supports more features than tokio_tungstenite. It is well maintained and each functionality is gated behind a feature flag, so it wont bloat your application with something you don't need. There is no benefit from moving to `tokio_tungstenite`.
