### ISSUE TITLE
Wrapping in WsStream removes Send and Sync properties

### ISSUE THREAD

**Issue by MathiasKoch** [najamelan/ws_stream_tungstenite#3]
Given a `WsStream<S>`, the restulting `WsStream` does not implement `std::marker::Send` & `std::marker::Sync` even if the inner type `S` does implement both.

This defeats usage of this in multi-threaded environments.

For reference, this can easily be checked by
```rust
// type S = <Any inner type implementing "AsyncRead + AsyncWrite + Unpin">;

#[test]
fn test() {
    fn is_send<T: Send>() {}
    is_send::<S>(); // compiles only if true
    is_send::<WsSteam<S>>(); // won't compile; see compile_fail rustdoc feature

    fn is_sync<T: Sync>() {}
    is_sync::<S>(); // compiles only if true
    is_sync::<WsSteam<S>>(); // won't compile; see compile_fail rustdoc feature
}
```

**Comment by najamelan** [comment]
As far as I can tell it should be possible to make it `Send`. I have to dig in a bit to see why it's not.

As for `Sync`, do you really need that? The traits this type provides all require to be polled as `Pin<&mut Self>`, so it seems hard to imagine a use case for `Sync`. 

What are you wanting to do exactly?

**Comment by najamelan** [comment]
Actually, according to [docs.rs](https://docs.rs/ws_stream_tungstenite/0.3.0/ws_stream_tungstenite/struct.WsStream.html) it is `Send`. Are you sure it's not?

**Comment by MathiasKoch** [comment]
I think you might be right, it looks like it is indeed `Send`.

I am attempting to add websocket support to the rumqtt client (https://github.com/bytebeamio/rumqtt), to get MQTT over Websockets, but they seem to have a weird requirement of `N: AsyncRead + AsyncWrite + Send + Sync + Unpin` for their network: https://github.com/bytebeamio/rumqtt/blob/ce4f6d9f4002b845f061dca2e93917ba2eea6924/rumqttc/src/framed.rs#L271

Maybe i should try opening an issue in rumqtt, asking why they insist on `Sync`?

**Comment by najamelan** [comment]
Ok, I see. I suspect this is a mistake on their part, as you can't do anything with a `&AsyncRead`. You always need `mut`. It's probably because they want their `Network` object to be `Sync` and since they box, they cannot get the compiler to infere it (as opposed to when it is a generic parameter). 

So I think the solutions are:
- they remove the bound and add `unsafe impl Sync` to their `Network` type if they want that to be `Sync`
- add an `unsafe impl Sync` to `WsStream.

I personally am not really fond of adding `unsafe` to ws_stream_tungstenite as it currently has `#[ forbid(unsafe_code) ]`, but it's not entirely impossible. The problem is I then have to manually guarantee it is actually safe, which is always a risk, especially if the code base changes in the future. 

It currently isn't `Sync` because it holds a `pharos::Pharos` object, but I don't think there is a way to manipulate that without mutable access, so probably it's safe. The problem is that users can create shared mutable access with `Mutex` for example. These types simply aren't meant to be accessed from shared references. 

Are you ok with checking with the rumqtt maintainers to see what they think? 

In the mean time you could play around with it with a patched version of either lib to make those changes and test what it gives. Also if you are wanting to use this from a browser, make sure rumqtt compiles on WASM as well. If it's not from the browser, you shouldn't need websockets but probably just use TCP directly.

**Comment by MathiasKoch** [comment]
> I suspect this is a mistake on their part, as you can't do anything with a `&AsyncRead`.

I suspect you are absolutely right.

> Are you ok with checking with the rumqtt maintainers to see what they think

Yes, that is no problem for me! I would like the safe version as well!

> Also if you are wanting to use this from a browser, make sure rumqtt compiles on WASM as well. If it's not from the browser, you shouldn't need websockets but probably just use TCP directly.

I have no intention of using this from a browser. Actually in my use case, I want to use it from a CLI tool, but i want it to be over websockets rather than TCP, as AWS allows for a presigned authentification using credentials rather than key+certificate, making it much more feasible for a CLI tool, that is to be distributed in our intire cooporation as internal tool. https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html
