### ISSUE TITLE
Implement WsStream with Sync

### ISSUE THREAD

**Issue by IniterWorker** [najamelan/ws_stream_tungstenite#8]
Hi,

Based on https://github.com/najamelan/ws_stream_wasm/commit/d9a09165f6908de8c72455e7679a3ba1c9122a40,

Is it possible/easy to make WsStream thread safe in this crate too?

```
error[E0277]: `(dyn for<'r> FnMut(&'r WsEvent) -> bool + std::marker::Send + 'static)` cannot be shared between threads safely
   --> rumqttd/src/lib.rs:466:42
    |
466 | ...                   Network::new(WsStream::new(stream), max_incoming_size)
    |                       ------------ ^^^^^^^^^^^^^^^^^^^^^ `(dyn for<'r> FnMut(&'r WsEvent) -> bool + std::marker::Send + 'static)` cannot be shared between threads safely
```

Best regards,

**Comment by najamelan** [comment]
Hi, 

I didnt have linux open for a few days, sorry for the delay. I will look into it tomorrow. It looks like `async_tungstenite::WebsocketStream` is `Sync`, so in principle it should be possible, however, you wont be able to use `AsyncRead` or `AsyncWrite` functionality on it because those require `&mut`. So I wonder, why do you want this over using a mpsc channel to send your messages from one thread?
